---

- name: DNSMasq | package
  tags:
    - package
  package:
    name:
      - dnsmasq
      - dnsmasq-utils

- name: DNSmasq | static config
  tags:
  - config
  template:
    src : "{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
    group: "{{ dnsmasq_group }}"
    mode: 0640
  loop:
    - { src: dnsmasq.conf, dest: /etc/ }
    - { src: dnsmasq, dest: /etc/default/ }
    - { src: servers, dest: "{{ dnsmasq_conf_dir }}" }
  notify: restart dnsmasq

- name: DNSMasq | config subdirs
  tags:
    - dir
  file:
    path: "{{ dnsmasq_conf_dir ~ item }}"
    state: directory
    group: "{{ dnsmasq_group }}"
    mode: 0750
  loop: "{{ q('list', dnsmasq_dirs) }}"

- name: DNSmasq | dynamic config in subdirs
  tags:
    - config
  template:
    src : "{{ item }}.j2"
    dest: "{{ dnsmasq_conf_dir ~ item ~ '/' ~ item }}"
    group: "{{ dnsmasq_group }}"
    mode: 0640
  loop: "{{ q('list', dnsmasq_dirs) }}"

- name: DNSmasq | adblock lists
  tags:
    - config
  get_url:
    url : "{{ item.value }}"
    dest: "{{ dnsmasq_conf_dir ~ 'hosts/' ~ item.key }}"
    group: "{{ dnsmasq_group }}"
    mode: 0640
  loop: "{{ q('dict', adblock_urls) }}"

- name: DNSmasq | logrotate
  tags:
    - logrotate
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/dnsmasq

- name: DNSMasq | service
  tags:
  - service
  service:
    name: dnsmasq
    state: started
    enabled: yes
