---

- name: DNSMasq | package
  tags:
  - package
  package:
    name: "{{ item }}"
  with_items:
    - dnsmasq
    - dnsmasq-utils

- name: DNSMasq | dirs
  tags:
    - dir
  file:
    path: "{{ item.value }}"
    state: directory
    group: "{{ dnsmasq_group }}"
    mode: 0750
  with_dict: "{{ dnsmasq_dirs }}"

- name: DNSmasq | static config
  tags:
  - config
  template:
    src : "{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
    group: "{{ dnsmasq_group }}"
    mode: 0640
  with_items:
    - { src: dnsmasq.conf, dest: /etc/ }
    - { src: dnsmasq, dest: /etc/default/ }
    - { src: servers, dest: /etc/dnsmasq.d/.servers }
    - { src: logrotate.d/dnsmasq, dest: /etc }
  notify: restart dnsmasq

- name: DNSmasq | dynamic config in subdirs
  tags:
    - config
  template:
    src : "{{ item.key }}.j2"
    dest: "{{ item.value }}/{{ item.key }}"
    group: "{{ dnsmasq_group }}"
    mode: 0640
  with_dict: dnsmasq_dirs

- name: DNSmasq | adblock lists
  tags:
    - config
  get_url:
    url : "{{ item.value }}"
    dest: "{{ dnsmasq_dirs.hosts }}/adblock-{{ item.key }}"
    group: "{{ dnsmasq_group }}"
    mode: 0640
  with_dict: adblock_urls

- name: DNSMasq | service
  tags:
  - service
  service:
    name: dnsmasq
    state: started
    enabled: yes
