---

- name: DNSMasq | package
  tags:
    - package
  package:
    name:
      - dnsmasq
      - dnsmasq-utils

- name: DNSMasq | config subdirs
  tags:
    - dir
  file:
    path: "{{ dnsmasq_conf_dir }}/hosts"
    state: directory
    group: "{{ dnsmasq_group }}"
    mode: "0750"

# Requires a restart
- name: DNSmasq | config
  tags:
  - config
  template:
    src : "{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
    group: "{{ dnsmasq_group }}"
    mode: "0640"
  loop:
    - { src: dnsmasq.conf, dest: /etc }
    - { src: dnsmasq, dest: /etc/default }
  notify: restart dnsmasq

# Only requires a reload (HUP)
- name: DNSmasq | auxiliary config
  tags:
  - config
  template:
    src : "{{ item.src }}.j2"
    dest: "{{ dnsmasq_conf_dir }}/{{ item.dest | d() }}/{{ item.src }}"
    group: "{{ dnsmasq_group }}"
    mode: "0640"
  loop:
    - { src: servers }
    - { src: dhcp-hosts }
    - { src: dhcp-opts }
    - { src: hosts, dest: "hosts" }
  notify: reload dnsmasq

# Requires neither restart nor reload
- name: DNSmasq | host lists from URL
  tags:
    - config
  get_url:
    url : "{{ item.value }}"
    dest: "{{ dnsmasq_conf_dir }}/hosts/{{ item.key }}"
    group: "{{ dnsmasq_group }}"
    mode: "0640"
  loop: "{{ q('dict', dnsmasq_host_urls) }}"

- name: DNSMasq | service
  tags:
  - service
  service:
    name: dnsmasq
    state: started
    enabled: yes
