---

- name: DNSMasq | package
  tags:
  - package
  package:
    name:
    - dnsmasq
    - dnsmasq-utils

- name: DNSMasq | config subdirs
  tags:
  - dir
  file:
    path: "{{ item.dir }}"
    state: directory
    group: "{{ item.group | default(omit) }}"
    mode:  "{{ item.mode  | default(omit) }}"
  loop:
  - dir: "{{ dnsmasq_conf_dir }}/hosts"
    group: "{{ dnsmasq_group }}"
    mode: "0750"
  - dir: "{{ dnsmasq_conf_dir }}/includes"
    group: "{{ dnsmasq_group }}"
    mode: "0750"
  - dir: "{{ dnsmasq_iptables_conf | dirname }}"

# Requires a restart
- name: DNSmasq | config
  tags:
  - config
  template:
    src : "{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
    group: "{{ item.group | d(omit) }}"
    mode:  "{{ item.mode  | d(omit) }}"
  loop:
  - src: dnsmasq.conf
    dest: /etc
    group: "{{ dnsmasq_group }}"
    mode: 0640
  - src: dnsmasq
    dest: /etc/default
    group: "{{ dnsmasq_group }}"
    mode: 0640
  - src: iptables.conf
    dest: "{{ dnsmasq_iptables_conf | dirname }}"
  notify:
  - daemon-reload
  - restart dnsmasq

# Requires a restart
- name: DNSmasq | config from URL
  tags:
  - config
  get_url:
    url : "{{ item.value }}"
    dest: "{{ dnsmasq_conf_dir }}/includes/{{ item.key }}.conf"
    group: "{{ dnsmasq_group }}"
    mode: "0640"
    force: yes
  loop: "{{ q('dict', dnsmasq_includes) }}"

# Only requires a reload (HUP)
- name: DNSmasq | upstream DNS servers
  tags:
  - config
  template:
    src : servers.j2
    dest: "{{ dnsmasq_conf_dir }}/servers"
    group: "{{ dnsmasq_group }}"
    mode: "0640"
  notify: reload dnsmasq
  when: dnsmasq_servers

# Only requires a reload (HUP)
- name: DNSmasq | DHCP host config
  tags:
  - config
  template:
    src : dhcp-hosts.j2
    dest: "{{ dnsmasq_conf_dir }}/dhcp-hosts"
    group: "{{ dnsmasq_group }}"
    mode: "0640"
  notify: reload dnsmasq
  when: dnsmasq_dhcp_hosts

# Only requires a reload (HUP)
- name: DNSmasq | DHCP options
  tags:
  - config
  template:
    src : dhcp-opts.j2
    dest: "{{ dnsmasq_conf_dir }}/dhcp-opts"
    group: "{{ dnsmasq_group }}"
    mode: "0640"
  notify: reload dnsmasq
  when: dnsmasq_dhcp_opts

# Requires neither restart nor reload
- name: DNSmasq | static hosts
  tags:
  - config
  template:
    src : hosts.j2
    dest: "{{ dnsmasq_conf_dir }}/hosts/hosts"
    group: "{{ dnsmasq_group }}"
    mode: "0640"
  when: dnsmasq_hosts

- name: DNSMasq | service
  tags:
  - service
  service:
    name: dnsmasq
    state: started
    enabled: yes
