---

- name: DNSMasq | package
  tags:
  - package
  package:
    name: "{{ item }}"
  with_items:
    - dnsmasq
    - dnsmasq-utils

- name: DNSMasq | dirs
  tags:
    - dir
  file:
    path: "{{ item.value }}"
    state: directory
    group: "{{ dnsmasq_group }}"
    mode: 0750
  with_dict: dnsmasq_dirs

- name: DNSmasq | config (template)
  tags:
  - config
  template:
    src : "{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
    group: "{{ dnsmasq_group }}"
    mode: 0640
  with_items:
    - { src: dnsmasq.conf, dest: /etc/ }
    - { src: dnsmasq, dest: /etc/default/ }
    - { src: servers, dest: /etc/dnsmasq.d/.servers }
  notify: restart dnsmasq

- name: DNSmasq | config in dirs
  tags:
    - config
  template:
    src : "{{ item.key }}.j2"
    dest: "{{ item.value }}/{{ item.key }}"
    group: "{{ dnsmasq_group }}"
    mode: 0640
  with_dict: dnsmasq_dirs

- name: DNSmasq | adblock list
  tags:
    - config
  get_url:
    url : "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts"
    dest: "{{ dnsmasq_dirs.hosts }}/adblock"
    group: "{{ dnsmasq_group }}"
    mode: 0640

- name: DNSMasq | service
  tags:
  - service
  service:
    name: dnsmasq
    state: started
    enabled: yes
